services:
  # =============================================================================
  # INFRAESTRUTURA DE DADOS (Docker Compose)
  # =============================================================================

  postgres:
    image: postgres:15-alpine
    container_name: sparrow-postgres
    environment:
      POSTGRES_DB: system_design
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - sparrow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sparrow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sparrow-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: sparrow-redpanda
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
      - --kafka-addr 0.0.0.0:9092
      - --advertise-kafka-addr localhost:9092
      - --rpc-addr 0.0.0.0:8081
      - --advertise-rpc-addr localhost:8081
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - sparrow-network
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 30s
      timeout: 10s
      retries: 5

  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: sparrow-cockroachdb
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroachdb_data:/cockroach/cockroach-data
    networks:
      - sparrow-network
    healthcheck:
      test: ["CMD", "cockroach", "node", "status", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 5

  # =============================================================================
  # DESENVOLVIMENTO
  # =============================================================================

  registry:
    image: registry:2
    container_name: sparrow-registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - sparrow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/v2/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =============================================================================
  # FERRAMENTAS DE DESENVOLVIMENTO
  # =============================================================================

  k6:
    image: grafana/k6:latest
    container_name: sparrow-k6
    volumes:
      - ./load/k6:/scripts
    working_dir: /scripts
    networks:
      - sparrow-network
    profiles:
      - load-testing

volumes:
  postgres_data:
  redis_data:
  redpanda_data:
  cockroachdb_data:
  registry_data:

networks:
  sparrow-network:
    driver: bridge
