# =============================================================================
# Promtail Helm Values Template
# =============================================================================

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m

config:
  server:
    http_listen_port: 9080
    grpc_listen_port: 0
  positions:
    filename: /tmp/positions.yaml
  clients:
    - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      pipeline_stages:
        - docker: {}
