apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: ${loki_url}
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
    secureJsonData: {}
