# =============================================================================
# ArgoCD Helm Values Template
# =============================================================================

server:
  ingress:
    enabled: false

  service:
    type: NodePort
    nodePort: 30080

  extraArgs:
    - --insecure

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

repoServer:
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

applicationSet:
  enabled: false

redis:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m

# Global ArgoCD configuration
configs:
  secret:
    # Admin password (bcrypt hash)
    argocdServerAdminPassword: $2y$05$d9wAhFgvNUF2lH4OHD7mwubSKgdYewWHD824KmGEsRg7OyRj4kdVG

  cm:
    # URL configuration
    url: "https://argocd.local"

    # OIDC configuration (can be overridden)
    oidc.config: |
      name: OIDC
      issuer: https://your-oidc-provider.com
      clientId: argocd
      requestedScopes: ["openid", "profile", "email", "groups"]

    # Resource customizations
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs
